push-wrapper: tidying

diff --git a/toplevel-things/cljfmt-with-local-formatting--push-wrapper/hooks/pre-push b/toplevel-things/cljfmt-with-local-formatting--push-wrapper/hooks/pre-push
--- a/toplevel-things/cljfmt-with-local-formatting--push-wrapper/hooks/pre-push
+++ b/toplevel-things/cljfmt-with-local-formatting--push-wrapper/hooks/pre-push
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-if [ ! -f .git/_nomis-in-pre-push-wrapper ]; then
-    >&2 echo 'ERROR: The pre-push hook says: Instead of `git push`, you need to use the push wrapper script. See the docs.'
+stdin=$(cat);
+
+if [ ! -z "${stdin}" ]
+then
+    >&2 echo 'ERROR: Instead of `git push`, use the `nomis-cljfmt-with-local-formatting--push-wrapper--git-push` wrapper script so that cljfmt formatting is applied. See the docs.'
     exit 1
 fi
